# Generated by Django 4.2.14 on 2024-08-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_featured',
        ),
    ]
