# Generated by Django 4.2.14 on 2024-08-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('creator', 'Course Creator')], default='student', max_length=10),
        ),
    ]
