# Generated by Django 4.2.14 on 2024-08-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video_file',
        ),
    ]
