# Generated by Django 4.2.14 on 2024-08-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_course_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/'),
        ),
    ]
