# Generated by Django 4.2.14 on 2024-09-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
